### PR TITLE
Cadzow для MSSA, c медленной коррекцией

### PR DESCRIPTION
**Pull request by furiousbean**

### CODE REVIEW

**Comment by furiousbean** [comment]
Some test addition

**Comment by furiousbean** [comment]
Done

**Comment by eodus** [comment]
Cool.

And, please, remove old commit names from commits' messages (use rebase -i + reword)

**Comment by asl** [comment]
Please rework the stuff using the new clone

**Comment by furiousbean** [comment]
done

**Comment by furiousbean** [comment]
The main difference is usage of .to.series.list() and unlist(.to.series.list(...)) instead of just passing vector. Algorithms seem to be equal.

**Comment by asl** [comment]
Ok. Please rebase & squash the stuff, so it can be reviewed as a whole now

**Comment by furiousbean** [comment]
Done.

**Comment by asl** [comment]
I believe .to.series.list should work fine with just vector (converting it to list of length 1). And thus the algorithms can be merged.

There is no need for "mcadzow" and all that stuff with evaluation and call patching. The reason I did so with cadzow.1d.ssa is just because I wanted to forward the arguments without tossing with ...

**Comment by furiousbean** [comment]
Hmm, I removed "cadzow.ssa" code, renamed "mcadzow" to "cadzow.ssa", tried to run cadzow on just vector and it failed. Traceback is here: http://pastebin.com/S0iHSFph .
".to.series.list" always return list object, and "reconstruct" fails when "s" is a list of length = 1 instead of a vector. I think that patching ".to.series.list", which would make it always return a vector when the argument is vector isn't allowed due to corrupting ".to.series.list" semantics, so we have two ways: make "reconstruct" work with list of length = 1 or run ".to.series.list" depending to the type of "x".

**Comment by furiousbean** [comment]
Workaround done.

**Comment by asl** [comment]
I do not like this workaround. The reason is pretty simply - there is no way for user to use this option. It's basically for internal use only.

My point is: can't we just always use MSSA? Even for 1D-SSA. I do not think we'll loose bunch of functionality in this case.

**Comment by furiousbean** [comment]
But that means that we must change the "kind" of "ssa" object from "1d-ssa" to "mssa" in this case to make reconstruction work correctly. And then replace "kind" with old value, i.e. "1d-ssa", right?

Or just detect the kind of "ssa" object inside "cadzow.ssa"? Or make "convert" invisible for user by refactoring cadzow.ssa? This approach looks better.

**Comment by asl** [comment]
cadzow.something-specialized is always a some sort of wrapper. In the contrast, cadzow.ssa is a generic implementation and should always iterate via reconstruct / decompose steps (assuming that the operations of 'F" object are implemented - this was one of the main motivations of all that series.list class).

Now, both cadzow.1d.ssa and cadzow.mssa should all be the wrappers. However, the main workhorse should be .mssa and 1d.ssa should only make necessary lifting: inside cadzow.1d.ssa fallback to cadzow.mssa (with changed class, yes), grab the result and carefully unlist it (preserving the attributes of the series).

**Comment by furiousbean** [comment]
Got it.

**Comment by furiousbean** [comment]
I've done it.

**Comment by eodus** [comment]
This stuff already implemented. Thanks to everybody! =)

**Pull request closed without merging**
